
SET(GPAC
    '_fout_register'
    '_fin_register'
    '_vout_register'
    '_aout_register'
    '_resample_register'
    '_reframer_register'
    '_writegen_register'
    '_compositor_register'
    '_main'
)

SET(PTHREADS
    '_pthread_mutex_init'
    '_pthread_mutex_lock'
    '_pthread_mutex_unlock'
    '_pthread_mutex_destroy'
    '_posix_memalign'
    '_logs_mx'
)

SET(COMPOSITOR
   '_gf_sc_check_sys_frame'
   '_gf_input_sensor_setup_object'
)

SET(STDLIB
    '_vsnprintf'
    '_sprintf'
    '_siprintf'
    '_sscanf'
    '_snprintf'
    '___small_sprintf'
    '_stdout'
    '_stderr'
    '_memmove'
    '_calloc'
    '_realloc'
    '_memcmp'
    '_memchr'
    '_memcpy'
    '_free'
    '_memalign'
    '_getenv'
    '_strcasecmp'
    '_strcmp'
    '_strncasecmp'
    '_strncat'
    '_strncmp'
    '_strcspn'
    '_strspn'
    '_strcpy'
    '_strstr'
    '_strrchr'
    '_strchr'
    '_strlen'
    '_strtol'
    '_strdup'
    '_strcat'
    '_memset'
    '_exp2'
    '_atanf'
    '_sinf'
    '_bsearch'
    '_strtod'
    '_frexp'
    '_llrint'
    '_fabs'
    '_exp'
    '_exp2f'
    '_acos'
    '_asin'
    '_atan'
    '_sinh'
    '_tanh'
    '_tan'
    '_cosh'
    '_pow'
    '_qsort'
    '_log'
    '_log2f'
    '_cos'
    '_sin'
    '_ldexp'
    '_abs'
    '_srand'
    '_rand'
    '_round'
    '_roundf'
    '_open'
    '_fcntl'
    '_fstat'
    '_lseek'
    '_read'
    '_close'
    '_lrintf'
    '_fwrite'
    '_log10f'
    '_cbrt'
    '_atoi'
    '_strerror_r'
    '_iconv_open'
    '___multi3'
    '_gmtime_r'
    '_isalnum'
    '_fmemopen'
    '_fread'
    '_fclose'
    '_fiprintf'
    '_fputc'
)

SET(EMSCRIPTEN
    '_emscripten_longjmp'
    '_saveSetjmp'
    '___threwValue'
    '___THREW__'
)

SET(SOLVER
    '_get_properties'
    '_set_properties'
    '_destroy'
)

SET(EXTERNAL_FN
    ${GPAC}
    ${COMPOSITOR}
    ${EMSCRIPTEN}
    ${SOLVER}
    ${PTHREADS}
    ${STDLIB}
)

 string(JOIN "," EXPORTED_FUNCTIONS ${EXTERNAL_FN})
